apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose.exe convert -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_PASSWORD_FILE
              value: /run/secrets/mysql-wp-password
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /run/secrets/mysql-root-password
            - name: MYSQL_USER
              value: wp
          image: mysql:8
          name: db
          volumeMounts:
            - mountPath: /run/secrets
              name: mysql-root-password
              subPath: mysql-root-password
            - mountPath: /run/secrets
              name: mysql-wp-password
              subPath: mysql-wp-password
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: mysql-root-password
          secret:
            items:
              - key: mysql-root-password
                path: mysql-root-password
            secretName: mysql-root-password
        - name: mysql-wp-password
          secret:
            items:
              - key: mysql-wp-password
                path: mysql-wp-password
            secretName: mysql-wp-password
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
