apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose.exe convert -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: db
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD_FILE
              value: /run/secrets/mysql-wp-password
            - name: WORDPRESS_DB_USER
              value: wp
          image: wordpress:6.4
          name: wordpress
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: mysql-wp-password
              subPath: mysql-wp-password
      restartPolicy: Always
      volumes:
        - name: mysql-wp-password
          secret:
            items:
              - key: mysql-wp-password
                path: mysql-wp-password
            secretName: mysql-wp-password
